### ISSUE TITLE
Prevent kubectl to override kubectl-login's valid token with an expired one

### ISSUE THREAD

**Issue by anderseknert** [Bisnode/kubectl-login#4]
With the current behavior of the kubectl client, any token provided in `KUBECONFIG` will overwrite that provided by the exec credential plugin. This obviously works for as long as the token is valid, but results in a just as obvious 401 response when provided with an expired token, which in our case will happen about once a day - enough to be annoying. Now there are two solutions to this:

1. Don't store/provide the token in KUBECONFIG at all but source it from some other file.
   Pros: Easy fix.
   Cons: All clients need update. Behavior remains in kubectl.
2. Fix kubectl.
    Pros: kubectl is improved(?). Client does not need update.
    Cons: kubectl needs update + backported fix. More work to be done.

**Done when**
Problem is resolved using either of the above solutions,

**Comment by lukasz-kaminski** [comment]
I'd go with fixing kubectl, as this problem seems to be applicable to a wider audience.

Also, I see first solution more as a workaround than a fix.

**Comment by anderseknert** [comment]
Yeah I'd like to think so too, but it's not entirely clear exactly what the fix would entail. It would either need to be one of:

1. Token provided by exec plugin always being preferred over one in `KUBECONFIG`. 
2. Exec plugin not triggered at all if credentials present in `KUBECONFIG`.

Since our workaround is cheap and solves our problems I'll probably pursue that while waiting to see what the suggested change would be in kubectl's behavior, if even any.

**Comment by anderseknert** [comment]
Closing in this board as the issue is solved for our use case. Will keep track of the kubectl issue in the kubernetes project instead.
